[simulation]
gui = False
max_steps = 1500
n_cars_generated = 2000
green_duration = 10
yellow_duration = 4
num_episodes = 5
episode_seed_start = 100

[agent]
num_states = 24
num_actions = 4
gamma = 0.75
; action_mode options: traditional (DQN), one-step (rollout), greedy (g-only), manual (fixed-time)
action_mode = one-step

[dir]
models_path_name = new_model
experiment_name = dqn_24state_waitreward
model_to_test = 1
sumocfg_file_name = sumo_config.sumocfg
